account_id = "1aae59053cbd3b9add9d49e89d5143ab"
name = "securrency-test"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-11-15"




























