account_id = "1aae59053cbd3b9add9d49e89d5143ab"
name = "securrency-test"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-11-15"
main = "./worker/script.js"
[build]
command = "npm run build"
[build.upload]
format = "service-worker"




























